[package]
name = "rust-cli-file-uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "multipart"] }
clap = { version = "4.0", features = ["derive"] }
